language: node_js
node_js:
  - "node"
cache:
  directories:
    - ~/.npm
stages:
  - test
  - release
jobs:
  include:
    - stage: test
      node_js: lts/*
      script:
        - npm run test || true
        - npm run docs
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        local-dir: docs
        on:
          branch: master
          repo: eventOneHQ/apkup
    - stage: release
      node_js: lts/*
      deploy:
        - provider: script
          skip_cleanup: true
          script: npx semantic-release
          on:
            branch: next
            repo: eventOneHQ/apkup
        - provider: script
          skip_cleanup: true
          script: npx semantic-release
          on:
            branch: beta
            repo: eventOneHQ/apkup
notifications:
  email: false
